[project]
name = "mininet-example"
version = "0.1.0"
description = ""
requires-python = ">=3.10"
dependencies = [
    "mininet (>=2.3.0.dev6,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
